/* Browser bundle — generated by scripts/sync-concern-router.mjs. Do not edit by hand. */
(function (global) {
  "use strict";
  /**
   * AuditState — mirrors cell/contracts/CellStorage.sol CellTypeDefs.AuditState.
   * Single source for indexers; on-chain auditStateOf() returns these uint8 values.
   */
  
  const AuditState = {
    None: 0,
    Submitted: 1,
    Assigned: 2,
    InAudit: 3,
    AwaitingWindow: 4,
    Audited: 5,
    InBlock: 6,
    Claimed: 7,
    Exploited: 8,
    Invalidated: 9,
  };
  
  /** @param {number} index */
  function auditStateName(index) {
    return Object.keys(AuditState).find((k) => AuditState[k] === index) ?? null;
  }
  

  /**
   * Concern router (L-24) -- "Something looks wrong?" deterministic signpost.
   * Spec: body/proposals/concern-router-proposal.txt
   *
   * PURE function. Reads NORMALIZED chain facts + up to 3 plain answers -> exactly ONE lane
   * (or the next question to ask). Same inputs -> same lane, every time. No randomness, no clock.
   *
   * Interpretation channel only: never settles, pays, slashes, re-audits, or touches the cell.
   * FMEA gaps decorate the result card; they NEVER change the lane.
   *
   * Caller (indexer / concern.html) normalizes raw cell views into:
   *   state, claimOpen, disputeOpen, integrityOpen, specChallengeOpen,
   *   scope {status,covered,notChecked}, requiredStake, bounty, fmeaGaps[], claimFilingAllowed
   *
   * Usage:  node deriveConcernRouter.test.mjs
   */
  
  
  const Lane = {
    AlreadyHandled: "already-handled",
    ReCheckFirst: "re-check-first",
    PossibleMismatch: "possible-mismatch",
    ClaimNotOpen: "claim-not-open",
    ChecksOut: "checks-out",
    Integrity: "integrity",
    SpecGap: "spec-gap",
    ReadTheList: "read-the-list",
    Structural: "structural",
    Lost: "lost",
  };
  
  const Question = { Verify: "verify", Scope: "scope" };
  
  const PRE_WINDOW = new Set([AuditState.None, AuditState.Submitted, AuditState.Assigned, AuditState.InAudit]);
  const RESOLVED_OR_DISPUTING = new Set([AuditState.Claimed, AuditState.Exploited, AuditState.Invalidated]);
  
  function autoHandledReason(chain) {
    const s = chain.state;
    if (RESOLVED_OR_DISPUTING.has(s)) return "audit is already resolved or in dispute -- watch the explorer";
    if (chain.claimOpen) return "a vulnerability claim is already open -- watch, don't duplicate";
    if (chain.disputeOpen) return "a dispute re-audit is already open -- watch";
    if (chain.integrityOpen) return "an integrity review is already open -- watch";
    if (chain.specChallengeOpen) return "a spec challenge is already open -- watch";
    if (PRE_WINDOW.has(s)) return "audit is still in progress (not yet in its window) -- nothing to act on yet";
    return null;
  }
  
  function pickFacts(chain) {
    const scope = chain.scope || null;
    return {
      state: chain.state ?? null,
      stateName: auditStateName(chain.state),
      requiredStake: chain.requiredStake ?? null,
      bounty: chain.bounty ?? null,
      scope: scope ? { status: scope.status ?? null, covered: scope.covered ?? [], notChecked: scope.notChecked ?? [] } : null,
      fmeaGaps: Array.isArray(chain.fmeaGaps) ? chain.fmeaGaps : [],
      claimFilingAllowed: chain.claimFilingAllowed !== false,
    };
  }
  
  const out = (lane, reason, chain) => ({ lane, reason, ask: null, facts: pickFacts(chain) });
  const ask = (question, chain) => ({ lane: null, reason: `need answer: ${question}`, ask: question, facts: pickFacts(chain) });
  
  function deriveConcernRouter({ chain = {}, answers = {} } = {}) {
    if (answers.concern === "tool") {
      return out(Lane.Structural, "user reports the network tool itself, not this one audit", chain);
    }
    const handled = autoHandledReason(chain);
    if (handled) return out(Lane.AlreadyHandled, handled, chain);
  
    switch (answers.verify) {
      case undefined:
      case null:
        return ask(Question.Verify, chain);
      case "not-run":
      case "unsure-how":
        return out(Lane.ReCheckFirst, "has not re-run the audit's check (no wallet needed)", chain);
      case "different":
        return chain.claimFilingAllowed === false
          ? out(Lane.ClaimNotOpen, "re-run mismatch reported but cell will not accept a new claim on this audit", chain)
          : out(Lane.PossibleMismatch, "re-run produced a different result than the recorded one", chain);
      case "same":
        break;
      default:
        return out(Lane.Lost, `unrecognized verify answer: ${String(answers.verify)}`, chain);
    }
  
    if (!chain.scope || chain.scope.status === "unavailable") {
      return out(Lane.ReadTheList, "declared scope is unavailable to display -- read/seek help first", chain);
    }
    if (chain.scope.status === "declared-empty") {
      return out(Lane.ReadTheList, "declared scope has no v0 categories -- read the spec artifact directly", chain);
    }
    switch (answers.worry) {
      case undefined:
      case null:
        return ask(Question.Scope, chain);
      case "off-list":
        return out(Lane.SpecGap, "worry is outside the audit's declared scope", chain);
      case "on-list":
        return answers.suspectsFaked
          ? out(Lane.Integrity, "check reproduces but user suspects a faked / gamed result", chain)
          : out(Lane.ChecksOut, "check reproduces and the worry is within the declared scope", chain);
      case "unsure":
        return out(Lane.ReadTheList, "unsure whether the worry is in the declared scope", chain);
      default:
        return out(Lane.Lost, `unrecognized scope answer: ${String(answers.worry)}`, chain);
    }
  }
  
  

  const STATE_ENUM = [
    "None",
    "Submitted",
    "Assigned",
    "InAudit",
    "AwaitingWindow",
    "Audited",
    "InBlock",
    "Claimed",
    "Exploited",
    "Invalidated",
  ];
  
  /**
   * Maps membrane view-model audit rows → normalized chain facts for deriveConcernRouter.
   * Spec: body/proposals/concern-router-proposal.txt
   */
  
  const INTEGRITY_OPEN = new Set([1, 2]); // Open, VerdictSubmitted
  
  /** @param {object} audit — view-model audit row from indexer.mjs */
  function auditRowToChainFacts(audit) {
    if (!audit) throw new Error("audit required");
    const stateIdx = typeof audit.state === "number"
      ? audit.state
      : STATE_ENUM.indexOf(audit.state);
    const scope = audit.scope ?? { status: "unavailable", covered: [], notChecked: [] };
    return {
      state: stateIdx >= 0 ? stateIdx : AuditState.None,
      claimOpen: !!(audit.claim && !audit.claim.resolved),
      disputeOpen: !!audit.hasOpenDispute,
      integrityOpen: INTEGRITY_OPEN.has(Number(audit.integrityReviewStatus ?? 0)),
      specChallengeOpen: !!audit.specChallengeActive,
      scope: {
        status: scope.status ?? "unavailable",
        covered: scope.covered ?? [],
        notChecked: scope.notChecked ?? [],
      },
      requiredStake: audit.claimStakeEth ?? null,
      bounty: audit.bounty ?? audit.bountyWei ?? null,
      claimFilingAllowed: !!audit.claimable,
      fmeaGaps: audit.fmea?.knownClassIds ?? [],
    };
  }
  
  /** Human-readable scope lines for Step 3. */
  function formatScopeList(scope) {
    if (!scope || scope.status === "unavailable") {
      return { html: "<p class=\"k\"><em>Declared scope not available for this audit — read the spec link below.</em></p>", items: [] };
    }
    const covered = scope.covered ?? [];
    if (scope.status === "declared-empty" || covered.length === 0) {
      return { html: "<p class=\"k\"><em>This audit declared an empty scope list.</em></p>", items: [] };
    }
    const items = covered.map((s) => (typeof s === "string" ? s : s.symbol ?? String(s)));
    const lis = items.map((s) => `<li><span class="mono">${escapeHtml(s)}</span></li>`).join("");
    return { html: `<ul class="k scope-list">${lis}</ul>`, items };
  }
  
  function escapeHtml(s) {
    return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }
  
  

  /**
   * Lane → UI card (titles, bodies, links). Interpretation only — not settlement.
   */
  
  const DISCLAIMER =
    "Suggestions only — the chain settles by reproduction, not this page.";
  
  /** @param {string} lane */
  function linksFor(lane, auditId) {
    const id = auditId ?? "";
    const ex = `explorer.html?id=${id}`;
    const manage = `manage.html?audit=${id}`;
    const map = {
      [Lane.AlreadyHandled]: [
        { label: "Back to audit record", href: ex },
        { label: "Walkthrough in section 3", href: "#appendNewcomer" },
        { label: "Verify in section 1", href: "#appendVerify" },
      ],
      [Lane.ReCheckFirst]: [
        { label: "Verify section below", href: "#appendVerify" },
        { label: "Manage (wallet)", href: manage },
      ],
      [Lane.PossibleMismatch]: [
        { label: "Manage — file a claim", href: manage },
        { label: "Bug-hunter guide", href: "bughunter.html" },
      ],
      [Lane.ClaimNotOpen]: [
        { label: "Back to audit record", href: ex },
        { label: "Verify section below", href: "#appendVerify" },
      ],
      [Lane.ChecksOut]: [
        { label: "Back to audit record", href: ex },
        { label: "How ideas become real", href: "ideas.html" },
      ],
      [Lane.Integrity]: [
        { label: "Bug-hunter — integrity path", href: "bughunter.html" },
        { label: "Manage (wallet)", href: manage },
      ],
      [Lane.SpecGap]: [
        { label: "Bug-hunter guide", href: "bughunter.html" },
        { label: "Spec-gap flow", href: "../../RealDeal/notebook/6-flows/book/06-spec-gap.md" },
      ],
      [Lane.ReadTheList]: [
        { label: "Back to audit record", href: ex },
        { label: "Verify section below", href: "#appendVerify" },
      ],
      [Lane.Structural]: [
        { label: "Structural upgrades", href: "docs-structural.html" },
        { label: "Phase G runbook", href: "phase-g-runbook.html" },
      ],
      [Lane.Lost]: [
        { label: "Bug-hunter quickstart", href: "bughunter.html" },
        { label: "Verify section below", href: "#appendVerify" },
      ],
    };
    return map[lane] ?? map[Lane.Lost];
  }
  
  const LANES = {
    [Lane.AlreadyHandled]: {
      title: "Already being handled — watch here",
      body: "The chain shows this audit is resolved, in dispute, or has an open overlay. Do not duplicate — follow progress in the explorer.",
    },
    [Lane.ReCheckFirst]: {
      title: "Re-check it yourself (no wallet)",
      body: "You have not re-run this audit's check yet. Recompute the result root on the pinned contract, then return if something still looks wrong.",
    },
    [Lane.PossibleMismatch]: {
      title: "You may have found a real problem",
      body: "You said your re-run gave a different answer than the chain recorded — so you may have caught something the audit got wrong. We haven't checked that here; only the network can, by re-running your result. If you're confident, the next step is to file a claim: connect a wallet, put down a refundable deposit, and submit your result on the Manage page (link below).",
    },
    [Lane.ClaimNotOpen]: {
      title: "Mismatch noted — claim path not open here",
      body: "You told us your re-run disagreed with the recorded result, but the chain will not accept a new vulnerability claim on this audit right now (wrong state, prior claim record, or not an ordinary audit row). Watch the explorer for state; re-verify before trying another path.",
    },
    [Lane.ChecksOut]: {
      title: "It checks out (by your report)",
      body: "You told us your re-run matched the recorded result and your worry is on the declared check list — we didn't verify either claim here. That does not prove the app is safe forever — only that this audit line may be internally consistent if your re-run was correct.",
    },
    [Lane.Integrity]: {
      title: "Looks right but feels gamed — integrity path",
      body: "You told us the check reproduced, but you suspect process abuse (wash / collusion). Integrity review is a separate staked overlay — not a bug claim on the declared check.",
    },
    [Lane.SpecGap]: {
      title: "Outside what was promised — report a spec gap",
      body: "You told us your re-run matched and your worry is outside what this audit declared it would check. Spec-gap is a separate overlay with its own stake and adoption economics.",
    },
    [Lane.ReadTheList]: {
      title: "Your re-run matched — now check the scope",
      body: "Good — your re-run matched the recorded result, so this audit is internally consistent. Whether that covers the thing you're worried about depends on what the audit actually promised to check (its declared scope). Compare your worry against that scope below; if no list is shown for this audit, open the verify guide to see how its checks were bound.",
    },
    [Lane.Structural]: {
      title: "The network tool itself may be wrong — advanced",
      body: "You believe the canonical network harness is wrong, not just this one audit. That is the structural upgrade railroad (gap → fix → jury) — not an ordinary claim.",
    },
    [Lane.Lost]: {
      title: "Not sure? Start here",
      body: "Your answers did not match a single escalated lane. Read the bug-hunter quickstart, verify an audit, then return.",
    },
  };

  function alreadyHandledCopy(routeResult) {
    const reason = String(routeResult.reason ?? "");
    const stateName = routeResult.facts?.stateName ?? "Unknown";

    if (reason.includes("still in progress")) {
      return {
        title: "Still in review — come back when the window opens",
        body:
          `On-chain status for this audit: ${stateName}. An auditor is still working, or the challenge window has not opened yet. ` +
          "You can still re-run verify in section 1 below, but filing a claim or using the walkthrough in section 3 usually waits until the audit is in Passed — window open or Settled. Watch the explorer for updates.",
      };
    }
    if (reason.includes("vulnerability claim")) {
      return {
        title: "A bug claim is already open on this audit",
        body:
          "Someone has already filed a vulnerability claim here. Do not file a duplicate — follow the claim and any dispute re-audit on the audit record.",
      };
    }
    if (reason.includes("dispute re-audit")) {
      return {
        title: "A dispute re-audit is already in progress",
        body:
          "The protocol opened an independent re-check on the original contract. Wait for that result — do not start a parallel path on this page.",
      };
    }
    if (reason.includes("integrity review")) {
      return {
        title: "An integrity review is already open",
        body:
          "A separate integrity overlay is active on this audit. Follow it on the audit record — this walkthrough is not the right door.",
      };
    }
    if (reason.includes("spec challenge")) {
      return {
        title: "A spec challenge is already open",
        body:
          "Someone is challenging whether the declared spec was auditable (Gate A). Follow that overlay on the audit record — not an ordinary bug claim.",
      };
    }
    if (reason.includes("resolved or in dispute")) {
      return {
        title: `${stateName} — follow the settled record`,
        body:
          `This audit is already in a resolved or disputing state (${stateName}). ` +
          "The walkthrough below is for choosing a next step when nothing serious is already in flight. Open the audit record to see what happened.",
      };
    }
    return {
      title: LANES[Lane.AlreadyHandled].title,
      body: LANES[Lane.AlreadyHandled].body,
    };
  }

  /**
   * @param {object} audit — view-model row
   * @param {{ lane: string|null, ask: string|null, reason: string, facts: object }} routeResult
   */
  function presentConcernRoute(audit, routeResult) {
    const lane = routeResult.lane;
    const def = LANES[lane] ?? LANES[Lane.Lost];
    const handled =
      lane === Lane.AlreadyHandled ? alreadyHandledCopy(routeResult) : null;
    const title = handled ? handled.title : def.title;
    const body = handled ? handled.body : def.body;
    const gaps = routeResult.facts?.fmeaGaps ?? [];
    const fmeaContext =
      gaps.length > 0
        ? {
            count: gaps.length,
            note:
              "Optional heads-up: the tool this audit used has missed some kinds of bugs before (that history is recorded on-chain). It is just background — it does not change the answer above, and it does not mean anything is wrong with this audit.",
          }
        : null;
    const CLAIM_LANES = [Lane.PossibleMismatch, Lane.Integrity, Lane.SpecGap];
    const preflight = CLAIM_LANES.includes(lane)
      ? [
          {
            label: "Can you file a claim right now?",
            ok: !!audit.claimable,
            detail: audit.claimable ? "Yes — this audit is open for a new claim" : "No — not open (already claimed, or wrong state)",
          },
          {
            label: "Refundable deposit to file",
            ok: true,
            detail: audit.claimStakeEth ? `${audit.claimStakeEth} AUDIT — returned if your claim holds` : "—",
          },
        ]
      : [];
    return {
      lane,
      ask: routeResult.ask,
      title,
      body,
      preflight,
      links: linksFor(lane, audit.id),
      chainSnapshot: {
        auditId: audit.id,
        state: audit.state,
        stakeEth: audit.claimStakeEth,
      },
      fmea: { knownClassIds: gaps },
      fmeaContext,
      disclaimer: DISCLAIMER,
      reason: routeResult.reason,
      facts: routeResult.facts,
    };
  }
  

  /**
   * Live Step 0 chain facts — eth_call refresh for concern.html (zero deps, browser-safe).
   * Refreshes only Step-0 routing fields; scope/FMEA stay on the indexed view-model row.
   */
  
  const CLAIM_ELIGIBLE = new Set([
    AuditState.AwaitingWindow,
    AuditState.Audited,
    AuditState.InBlock,
  ]);
  
  const DEFAULT_RPC = "https://sepolia.base.org";
  
  // Minimal keccak256 (same as verify.mjs — zero deps).
  const _KM = (1n << 64n) - 1n;
  const _KRC = [0x1n, 0x8082n, 0x800000000000808An, 0x8000000080008000n, 0x808Bn, 0x80000001n, 0x8000000080008081n, 0x8000000000008009n, 0x8An, 0x88n, 0x80008009n, 0x8000000An, 0x8000808Bn, 0x800000000000008Bn, 0x8000000000008089n, 0x8000000000008003n, 0x8000000000008002n, 0x8000000000000080n, 0x800An, 0x800000008000000An, 0x8000000080008081n, 0x8000000000008080n, 0x80000001n, 0x8000000080008008n];
  const _KRHO = [0, 1, 62, 28, 27, 36, 44, 6, 55, 20, 3, 10, 43, 25, 39, 41, 45, 15, 21, 8, 18, 2, 61, 56, 14];
  const _Krot = (x, n) => (n === 0n ? x : ((x << n) | (x >> (64n - n))) & _KM);
  function keccak256(input) {
    const S = new Array(25).fill(0n);
    const rate = 136;
    const len = input.length;
    const pl = Math.ceil((len + 1) / rate) * rate;
    const p = new Uint8Array(pl);
    p.set(input);
    p[len] ^= 1;
    p[pl - 1] ^= 0x80;
    for (let o = 0; o < pl; o += rate) {
      for (let i = 0; i < rate / 8; i++) {
        let l = 0n;
        for (let j = 0; j < 8; j++) l |= BigInt(p[o + i * 8 + j]) << (8n * BigInt(j));
        S[i] ^= l;
      }
      for (let r = 0; r < 24; r++) {
        const C = [0, 1, 2, 3, 4].map((x) => S[x] ^ S[x + 5] ^ S[x + 10] ^ S[x + 15] ^ S[x + 20]);
        const D = [0, 1, 2, 3, 4].map((x) => C[(x + 4) % 5] ^ _Krot(C[(x + 1) % 5], 1n));
        for (let x = 0; x < 5; x++) for (let y = 0; y < 5; y++) S[x + 5 * y] ^= D[x];
        const B = new Array(25).fill(0n);
        for (let x = 0; x < 5; x++) for (let y = 0; y < 5; y++) B[y + 5 * ((2 * x + 3 * y) % 5)] = _Krot(S[x + 5 * y], BigInt(_KRHO[x + 5 * y]));
        for (let x = 0; x < 5; x++) for (let y = 0; y < 5; y++) S[x + 5 * y] = B[x + 5 * y] ^ ((~B[(x + 1) % 5 + 5 * y]) & B[(x + 2) % 5 + 5 * y]) & _KM;
        S[0] ^= _KRC[r];
      }
    }
    const out = new Uint8Array(32);
    for (let i = 0; i < 4; i++) {
      let l = S[i];
      for (let j = 0; j < 8; j++) out[i * 8 + j] = Number((l >> (8n * BigInt(j))) & 0xffn);
    }
    return out;
  }
  
  /** @param {string} sig */
  function fnSelector(sig) {
    const hash = keccak256(new TextEncoder().encode(sig));
    const hex = [...hash].map((b) => b.toString(16).padStart(2, "0")).join("");
    return "0x" + hex.slice(0, 8);
  }
  
  /** @param {bigint | number | string} n */
  function padU256(n) {
    let x = BigInt(n);
    const out = new Uint8Array(32);
    for (let i = 31; i >= 0; i--) {
      out[i] = Number(x & 0xffn);
      x >>= 8n;
    }
    return out;
  }
  
  function bytesToHex(u) {
    return "0x" + [...u].map((b) => b.toString(16).padStart(2, "0")).join("");
  }
  
  /** @param {string} hex @param {number} wordIndex */
  function readWord(hex, wordIndex) {
    const s = hex.replace(/^0x/, "");
    const start = wordIndex * 64;
    return "0x" + s.slice(start, start + 64);
  }
  
  function readU8(hex, wordIndex) {
    return Number(BigInt(readWord(hex, wordIndex)) & 0xffn);
  }
  
  function readBool(hex, wordIndex) {
    return BigInt(readWord(hex, wordIndex)) !== 0n;
  }
  
  function readU256(hex, wordIndex) {
    return BigInt(readWord(hex, wordIndex));
  }
  
  /**
   * @param {string} rpcUrl
   * @param {string} to
   * @param {string} data
   */
  async function ethCall(rpcUrl, to, data) {
    const r = await fetch(rpcUrl, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        jsonrpc: "2.0",
        id: 1,
        method: "eth_call",
        params: [{ to, data }, "latest"],
      }),
    });
    const j = await r.json();
    if (j.error) throw new Error(j.error.message || JSON.stringify(j.error));
    return j.result;
  }
  
  /** Decode audits(uint256) static tuple (AuditCell getter order). */
  function decodeAuditsReturn(hex) {
    return {
      state: readU8(hex, 5),
      isVulnerabilityReport: readBool(hex, 12),
      isClaimDispute: readBool(hex, 13),
    };
  }
  
  /** Decode vulnerabilityClaims(uint256) tuple tail fields. */
  function decodeClaimReturn(hex) {
    return {
      resolved: readBool(hex, 5),
      exists: readBool(hex, 6),
    };
  }
  
  /**
   * @param {object} cfg
   * @param {string} cfg.cell
   * @param {number | bigint} cfg.auditId
   * @param {string} [cfg.rpcUrl]
   * @param {string | null} [cfg.integrityModule]
   * @param {string | null} [cfg.specArbiterModule]
   * @param {string} [cfg.auditKind] — view-model kind (audit | dispute | fix)
   */
  async function fetchStep0ChainFacts(cfg) {
    const rpcUrl = cfg.rpcUrl || DEFAULT_RPC;
    const cell = cfg.cell;
    const id = BigInt(cfg.auditId);
    const idHex = bytesToHex(padU256(id)).slice(2);
  
    const auditData = fnSelector("audits(uint256)") + idHex;
    const claimData = fnSelector("vulnerabilityClaims(uint256)") + idHex;
    const disputeData = fnSelector("activeDisputeAuditId(uint256)") + idHex;
  
    const [auditHex, claimHex, disputeHex] = await Promise.all([
      ethCall(rpcUrl, cell, auditData),
      ethCall(rpcUrl, cell, claimData),
      ethCall(rpcUrl, cell, disputeData),
    ]);
  
    const audit = decodeAuditsReturn(auditHex);
    const claim = decodeClaimReturn(claimHex);
    const disputeId = readU256(disputeHex, 0);
  
    let integrityOpen = false;
    if (cfg.integrityModule) {
      const ih = await ethCall(rpcUrl, cfg.integrityModule, fnSelector("integrityReviewStatusOf(uint256)") + idHex);
      integrityOpen = INTEGRITY_OPEN.has(readU8(ih, 0));
    }
  
    let specChallengeOpen = false;
    if (cfg.specArbiterModule) {
      const sh = await ethCall(
        rpcUrl,
        cfg.specArbiterModule,
        fnSelector("challengeActive(uint256)") + idHex,
      );
      specChallengeOpen = readBool(sh, 0);
    }
  
    const kind = cfg.auditKind ?? (audit.isClaimDispute ? "dispute" : audit.isVulnerabilityReport ? "fix" : "audit");
    const claimOpen = claim.exists && !claim.resolved;
    // Matches ClaimDisputeModule._claimEligible (AwaitingWindow | Audited | InBlock)
    // plus membrane/indexer: kind === "audit" && !vulnerabilityClaims(id).exists.
    // Does not check claimant identity (wallet path enforces that at tx time).
    const claimFilingAllowed = kind === "audit" && CLAIM_ELIGIBLE.has(audit.state) && !claim.exists;
  
    return {
      state: audit.state,
      claimOpen,
      claimExists: claim.exists,
      disputeOpen: disputeId > 0n,
      integrityOpen,
      specChallengeOpen,
      claimFilingAllowed,
      refreshedAt: new Date().toISOString(),
      source: "rpc",
    };
  }
  
  /**
   * Overlay live Step-0 fields onto chain facts from the indexed row.
   * @param {object} baseChain — auditRowToChainFacts(row)
   * @param {object} live — fetchStep0ChainFacts result
   */
  function mergeLiveStep0ChainFacts(baseChain, live) {
    if (!live) return baseChain;
    return {
      ...baseChain,
      state: live.state ?? baseChain.state,
      claimOpen: live.claimOpen ?? baseChain.claimOpen,
      disputeOpen: live.disputeOpen ?? baseChain.disputeOpen,
      integrityOpen: live.integrityOpen ?? baseChain.integrityOpen,
      specChallengeOpen: live.specChallengeOpen ?? baseChain.specChallengeOpen,
      claimFilingAllowed: live.claimFilingAllowed ?? baseChain.claimFilingAllowed,
      step0RefreshedAt: live.refreshedAt ?? null,
      step0Source: live.source ?? "indexed",
    };
  }
  
  /** Patch view-model audit row display fields after live refresh. */
  function patchAuditRowFromStep0(audit, live) {
    if (!audit || !live) return audit;
    const names = [
      "None", "Submitted", "Assigned", "InAudit", "AwaitingWindow", "Audited",
      "InBlock", "Claimed", "Exploited", "Invalidated",
    ];
    const next = { ...audit };
    if (live.state != null) next.state = names[live.state] ?? audit.state;
    next.claimable = !!live.claimFilingAllowed;
    next.hasOpenDispute = !!live.disputeOpen;
    if (live.claimOpen) {
      next.claim = { ...(audit.claim || {}), resolved: false };
    } else if (!live.claimExists) {
      next.claim = null;
    }
    next.integrityReviewStatus = live.integrityOpen ? 1 : 0;
    next.specChallengeActive = !!live.specChallengeOpen;
    next.step0RefreshedAt = live.refreshedAt;
    return next;
  }
  

  global.AuditState = AuditState;
  global.Lane = Lane;
  global.Question = Question;
  global.deriveConcernRouter = deriveConcernRouter;
  global.auditRowToChainFacts = auditRowToChainFacts;
  global.formatScopeList = formatScopeList;
  global.presentConcernRoute = presentConcernRoute;
  global.fetchStep0ChainFacts = fetchStep0ChainFacts;
  global.mergeLiveStep0ChainFacts = mergeLiveStep0ChainFacts;
  global.patchAuditRowFromStep0 = patchAuditRowFromStep0;
})(typeof window !== "undefined" ? window : globalThis);
